name: random_quote_generator
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  share_plus: ^7.0.4
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - android/assets/images/image1.jpg
    - android/assets/images/image2.jpg
    - android/assets/images/image3.jpeg
    - android/assets/images/image4.jpg
    - android/assets/images/image5.jpg
    - android/assets/images/image6.jpg
    - android/assets/images/image7.jpg
    - android/assets/images/image8.jpg
    - android/assets/images/image10.jpg
    - android/assets/images/image11.jpg
    - android/assets/images/image12.jpg
    - android/assets/images/image13.jpg
    - android/assets/images/image14.jpg
    - android/assets/images/image15.jpg
    - android/assets/images/image16.jpg
    - android/assets/images/image17.jpg
    - android/assets/images/image18.jpg
    - android/assets/images/image19.jpg
    - android/assets/images/image20.jpg

  # Fonts example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
