const quotes = [
  "Be yourself; everyone else is already taken.",
  "So many books, so little time.",
  "Two things are infinite: the universe and human stupidity; and I'm not sure about the universe.",
  "A room without books is like a body without a soul.",
  "Be who you are and say what you feel, because those who mind don't matter, and those who matter don't mind.",
  "You know you're in love when you can't fall asleep because reality is finally better than your dreams.",
  "You only live once, but if you do it right, once is enough.",
  "Be the change that you wish to see in the world.",
  "In three words I can sum up everything I've learned about life: it goes on.",
  "If you want to know what a man's like, take a good look at how he treats his inferiors, not his equals.",
  "Don’t walk in front of me… I may not follow Don’t walk behind me… I may not lead Walk beside me… just be my friend",
  "If you tell the truth, you don't have to remember anything.",
  'Friendship ... is born at the moment when one man says to another "What! You too? I thought that no one but myself . . .',
  "Impossible is just an opinion.",
  "Fail,but never quit.",
  "A friend is someone who knows all about you and still loves you.",
  "To live is the rarest thing in the world. Most people exist, that is all.",
  "Always forgive your enemies; nothing annoys them so much.",
  "Darkness cannot drive out darkness: only light can do that. Hate cannot drive out hate: only love can do that.",
  "Live as if you were to die tomorrow. Learn as if you were to live forever.",
  "We accept the love we think we deserve.",
  "I am so clever that sometimes I don't understand a single word of what I am saying.",
  "To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment.",
  "Insanity is doing the same thing, over and over again, but expecting different results.",
  "It is better to be hated for what you are than to be loved for what you are not.",
  "Many of life’s failures are people who did not realize how close they were to success when they gave up.",
  "Life is like a coin. You can spend it any way you wish, but you only spend it once.",
  "Never let the fear of striking out keep you from playing the game.",
  "Don’t settle for what life gives you; make life better and build something.",
  "I believe every human has a finite number of heartbeats. I don't intend to waste any of mine",
  "The best way to predict your future is to create it.",
  "If you want to live a happy life, tie it to a goal, not to people or things.",
  "You must expect great things of yourself before you can do them.",
 ];

const images = [
  'android/assets/images/image1.jpg',
  'android/assets/images/image2.jpg',
  'android/assets/images/image3.jpeg',
  'android/assets/images/image4.jpg',
  'android/assets/images/image5.jpg',
  'android/assets/images/image6.jpg',
  'android/assets/images/image7.jpg',
  'android/assets/images/image8.jpg',
  'android/assets/images/image10.jpg',
  'android/assets/images/image11.jpg',
  'android/assets/images/image12.jpg',
  'android/assets/images/image13.jpg',
  'android/assets/images/image14.jpg',
  'android/assets/images/image15.jpg',
  'android/assets/images/image16.jpg',
  'android/assets/images/image17.jpg',
  'android/assets/images/image18.jpg',
  'android/assets/images/image19.jpg',
  'android/assets/images/image20.jpg',
];